version: "3.9"
services:
  app:
    image: ${DOCKER_USER}/actions_test:${IMAGE_TAG:-stable}
    restart: always
    environment:
      - APP_ENV=prod
      - APP_VERSION=${APP_VERSION:-unknown}
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always