version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: autoscaling-flask:latest
    container_name: autoscaling-web
    restart: always
    ports:
      - "5000:5000"   
    environment:
      - PORT=5000
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=30
    # env_file:
    #   - .env
